<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="css/xml_style.css"?>
<!DOCTYPE rulespagecontent [ 
    <!ELEMENT rulespagecontent (pagename?, rule_group*)>
    <!ELEMENT pagename (#PCDATA)>
    <!ELEMENT rule_group (rule_title+,(rule_content|rule_list))+>
    <!ELEMENT rule_title (#PCDATA)>
    <!ELEMENT rule_content (#PCDATA)>
    <!ELEMENT rule_list (rule_list_value+)>
    <!ELEMENT rule_list_value (#PCDATA)>
]>
<rulespagecontent>
    <pagename>Squash Game Rules Page</pagename>
    <rule_group rulenumber="1st rule">
        <rule_title>Squash Scoring Rules</rule_title>
        <rule_content>The scoring rules are pretty simple. Usually a match will be in a “best-of-five” games format........</rule_content>
    </rule_group>
    <rule_group rulenumber="2nd rule">
        <rule_title>Warmup / Before the Match</rule_title>
        <rule_content paragraph="1">Before you begin a match, make sure to warm up the ball. The players.........</rule_content>
    </rule_group>
    <rule_group rulenumber="3rd rule">
        <rule_title>Squash Serve Rules</rule_title>
        <rule_list>
            <rule_list_value paragraph="1">You’re allowed to volley the return or let it bounce </rule_list_value>
            <rule_list_value paragraph="2">Your return must reach the front wall at some point, ........</rule_list_value>
            <rule_list_value paragraph="3">The ball can never go out of court or hit the tin</rule_list_value>
        </rule_list>
    </rule_group>
    <rule_group rulenumber="4th rule">
        <rule_title>Playing a Point</rule_title>
        <rule_content>After the serve, the players alternate shots..........</rule_content>
    </rule_group>
</rulespagecontent>